
dataWriter:
  bootstrapServers: "localhost:9092"
  producerName: "EZapp-dataWriter"
  writerTopicName: "documents"
  writerTopicPartitionCount: 6
  zookeeperHosts: "localhost:2181"
  writerTopicReplicationFactor: 1
elasticsearch:
    transportAddresses:
        - address: "localhost"
          port: 9300
queryBus:
  bootstrapServers: "localhost:9092"
  producerName: "EZapp-queryBus"
  queryBusTopicName: "queries"
  queryBusTopicPartitionCount: 1
  zookeeperHosts: "localhost:2181"
  queryBusTopicReplicationFactor: 1
rulesManager:
  zookeeperHosts: "localhost:2181"
  bootstrapTopicName: "bootstrapped-document-messages"
  shutdownTopicName: "shutdown-messages"
  partitionCount: 6
  replicationFactor: 1
  kafkaBootstrapServers: "localhost:9092"


