
dataWriter:
  bootstrapServers: "localhost:9092"
  producerName: "EZapp-dataWriter"
  writerTopicName: "documents"
  writerTopicPartitionCount: 1
  zookeeperHosts: "localhost:2181"
elasticConfiguration:
    transportAddresses:
        - address: "localhost"
          port: 9300
queryBus:
  bootstrapServers: "localhost:9092"
  producerName: "EZapp-queryBus"
  queryBusTopicName: "queries"
  queryBusTopicPartitionCount: 1
  zookeeperHosts: "localhost:2181"
